### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ASlayton** [nss-evening-cohort-7/chatty-coulrophobia#14]
# Story
As a developer, I need basic files in order to begin creating this app, I need to create and edit these files.

# Acceptance Criteria
**When**, the files and folders are created
**Then**, the developer will be able to start writing code
**And** the basic page will start to take shape.

# Technical Notes
- file structure:
```
.gitignore
index.html
styles/main.css
db/users.json
db/messages.json
javascripts/main.js
javascripts/messages.js
javascripts/add.js
javascripts/edit.js
javascripts/delete.js
javascripts/domStringBuilder.js
javascripts/printToDom.js
javascripts/objectBuilder.js
javascripts/themes.js
javascripts/events.js
javascripts/xhr.js
javascripts/messageGatekeeper.js
javascripts/emoji.js
javascripts/timestamp.js
lib/.eslintrc.json
lib/Gruntfile.js
```
- `npm init` inside the `lib` directory
- install `grunt` and the appropriate dependencies ( `npm install grunt matchdep grunt-contrib-watch grunt-browserify gruntify-eslint --save-dev` )
- copy data over for `.eslintrc.json` and `Gruntfile.js` from earlier projects
- setup HTML boilerplate, include jquery, bootstrap and `dist/app.js` script
- change background color using `styles.css` to ensure it works

**Comment by amillion3** [comment]
https://github.com/OneSignal/emoji-picker
https://www.npmjs.com/package/emoji-parser
