### ISSUE TITLE
Design message object format

### ISSUE THREAD

**Issue by johnachor** [nss-evening-cohort-7/chatty-coulrophobia#15]

**Comment by johnachor** [comment]
## Story
As a developer, I need a standardized object format for chat messages so I can work with consistent data.

## Acceptance critera
**WHEN** a new message is created
**THEN** it should become a Message Object with the standard key/value pairs to be passed to the appropriate functions.

## Technical notes
Currently known object key/value pairs needed:

message ID
username
original timestamp
edit timestamp
message string

**Comment by amillion3** [comment]
Part of the JSON data creation ticket.
