### ISSUE TITLE
Create default messages json

### ISSUE THREAD

**Issue by johnachor** [nss-evening-cohort-7/chatty-coulrophobia#17]

**Comment by johnachor** [comment]
## Story
As a developer, I need a database with five prewritten message objects for use on page load.

## Acceptance Critera
Create a db/messages.json file with five prepopulated message objects, using the standard structure.

**Comment by amillion3** [comment]
PR Link:
https://github.com/nss-evening-cohort-7/chatty-coulrophobia/pull/38
