### ISSUE TITLE
Delete Messages

### ISSUE THREAD

**Issue by amillion3** [nss-evening-cohort-7/chatty-coulrophobia#20]

**Comment by johnachor** [comment]
## Story
As a user, I should be able to remove existing messages from the app.

## Acceptance criteria
**WHEN** the Delete button of a message is pressed
**THEN** the message is removed from the DOM
**AND** the message object is removed from the message array

## Technical notes
Stretch goal: grab the next newest message from the backlog that is not currently displayed, and display it as the oldest message in the DOM.
