### ISSUE TITLE
Attach event listeners- main

### ISSUE THREAD

**Issue by ASlayton** [nss-evening-cohort-7/chatty-coulrophobia#23]
# Story
As developers, in order for the app to be functional immediately when user log into the page, we need to attach the event listeners to the DOM elements on page load.

# Acceptance Criteria
When page load
Then user should be able to click on "Clear Messages" button and delete all existing messages
Then the input field should be ready for user to send out message when press "Enter" key
Then the text should be enlarged when "Enlarge Text" is checked
Then the theme should be changed to dark when "Dark Theme" is checked
Then the custom theme module should be displayed when "Custom Theme" button is clicked
Then all the "Edit" and "Delete" buttons should be working for those 5 existing messages 

# Technical Notes
Create addEventListenersMain function to attach eventlisteners to: input field, "Clear Messages" button, "Enlarge Text" checkbox, "Dark Theme" checkbox, "Custom Theme",  and the main container that hold all messages

**Comment by amillion3** [comment]
Event listeners handled by each person on other tickets.
