### ISSUE TITLE
Emoji parsing

### ISSUE THREAD

**Issue by amillion3** [nss-evening-cohort-7/chatty-coulrophobia#26]

**Comment by johnachor** [comment]
## Story
As a user, I would like to be able to use emoji in my chat messages by typing parseable strings.

## Acceptance criteria
**WHEN** a message contains a string that parses as an emoji
**THEN** it should be replaced with the emoji when the message is printed to the DOM.

**Comment by johnachor** [comment]
Not necessary as emoji are now inserted as-is into the chat message.
