### ISSUE TITLE
Page layout

### ISSUE THREAD

**Issue by johnachor** [nss-evening-cohort-7/chatty-coulrophobia#27]
# Story
As a user, I want to see information on the page, in order to send messages, I need to have the data represented visually.

# Acceptance Criteria
**When**, a user visits the page
**Then**, the app will be well laid-out
**And** allow the user to see messages
**And** allow the user to edit, delete, or clear all messages
**And** the user will be able to select a dark theme or select a custom theme.

# Technical Notes
- `navbar` will go at the top and be fixed. This will be created in #13 
- Below the `navbar` will be a `<div class='container-fluid'></div>`
    - Make sure `navbar` is responsive.
- Inside that div will be a `<div class='messages-wrapper'></div>`
- The messages themselves will be created, edited, and deleted via JavaScript.
- Fonts/colors will be set here. (  [Google Fonts](https://fonts.google.com/) )

<img width="744" alt="screen shot 2018-04-21 at 12 26 00 pm" src="https://user-images.githubusercontent.com/20422019/39086988-3a911586-455f-11e8-99f3-6ec87a6f9d85.png">

**Comment by amillion3** [comment]
- Clown theme
- Users will have clown hair, clown noses, etc.
