### ISSUE TITLE
messageStringBuilder

### ISSUE THREAD

**Issue by amillion3** [nss-evening-cohort-7/chatty-coulrophobia#29]

**Comment by johnachor** [comment]
## Story
As a developer, I need to be able to convert message objects to HTML strings to insert into the DOM.

## Acceptance Criteria
**WHEN** a message needs to be printed to the DOM
**THEN** an HTML string should be created from the object data and passed to the printToDom function.

## Technical notes
A message string should consist of a div container with a message class, containing:
- the username
- the message ID (should this be visible to the user?)
- the timestamp (and, if appropriate, the last-edited timestamp)
- the message including any emoji
- an Edit button and a Delete button
